### ISSUE TITLE
Problem for variables with the same name

### ISSUE THREAD

**Issue by xiefengy** [laliberte/cdb_query#1]
When different variables with same variable name were asked, the program would not treat them as separate variables.

For example, if two variables $snw:day-landIce-day$ and $snw:mon-landIce-LImon$ are asked, the resulting pointer file would only have the later variable.

**Comment by laliberte** [comment]
Thanks @xiefengy!

This is a known limitation. It should be fairly easy to allow and I have already started some of the ground work for it.

**Comment by laliberte** [comment]
This issue should be solved by #4.
